# Generated by Django 5.2 on 2025-05-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_city', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='status',
            field=models.CharField(choices=[('inativo', 'inativo'), ('ativo', 'ativo')], max_length=50),
        ),
    ]
