# Generated by Django 5.2 on 2025-05-26 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_city', '0002_alter_sensor_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='tipo',
        ),
    ]
