# Generated by Django 5.2 on 2025-05-26 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_city', '0003_remove_usuario_tipo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
