# Generated by Django 5.2 on 2025-05-27 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_city', '0004_delete_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historico',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
